# Site settings
title: James Lennon
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: James Lennon
user_description: I started programming with DarkBasic and Python (Blender Game Engine) and made small games later with Allegro and GameMaker 7. Eventually I settled on Unity for a few years through version 5 until roughly a year after Unreal Engine 4 came out; I switched after the last Unity project was finished and never looked back.
user_title: Software Engineer
email: jl@amstaddigital.com
# twitter_username: lorem_ipsum
github_username:  iliags
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
