# Site settings
title: James Lennon
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: James Lennon
user_description: CIO and Unreal Engine developer at Amstad Digital.
user_title: Software Engineer
email: jl@amstaddigital.com
# twitter_username: lorem_ipsum
github_username:  iliags
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
